FROM node:16.14.0

ARG MYSQL_DEFAULT
ARG TOKEN_SECRET
ARG PORT
ENV MYSQL_DEFAULT=$MYSQL_DEFAULT
ENV TOKEN_SECRET=$TOKEN_SECRET
ENV PORT=$PORT

WORKDIR /usr/src/app
COPY package*.json ./
RUN yarn install
COPY . .
RUN yarn build

EXPOSE ${PORT}
CMD [ "yarn", "start" ]